// Website roster for khristiankline.com
window.KK_DEFAULT_WEBSITES = [
  {
    id: "gtm-insights",
    title: "GTM Insights Group",
    status: "live",
    client: "GTM Insights Group",
    year: "2026",
    category: "Consultant Site",
    summary: "Enterprise go-to-market consulting — digital & web intelligence that turns web properties into a measurable GTM advantage.",
    description: "Specialized consulting site for enterprise GTM teams. The practice delivers actionable digital and web insights so operators can execute go-to-market strategies with precision and measurable impact.\n\nPositioned for Fortune 500 GTM leaders: services, approach, projects, virtual events, and a clear path to book a strategy call.",
    role: "Founder · Strategy, design & front-end",
    stack: ["Next.js", "TypeScript", "Vercel"],
    url: "https://www.gtm-insights.com",
    screenshots: ["/media/websites/gtm-insights-home.jpg"],
    tone: "live"
  },
  {
    id: "watchmen-of-the-streets",
    title: "Watchmen of the Streets",
    status: "live",
    client: "Watchmen of the Streets",
    year: "2025",
    category: "Non-Profit",
    summary: "Homeless outreach of Habit Missions — field work, documentary storytelling, and a calm public presence for a boots-on-the-ground ministry.",
    description: "Nonprofit site for Watchmen of the Streets, a homeless outreach of Habit Missions. The public face balances documentary gravity with practical clarity: mission story, field photography, video, and simple paths to learn more, contact, and support.",
    role: "Design & development",
    stack: ["WordPress", "Custom theme", "Video"],
    url: "https://www.watchmenofthestreets.com",
    screenshots: ["/media/websites/watchmen-home.jpg"],
    tone: "live"
  },
  {
    id: "music-venue-live",
    title: "Music Venue Live",
    status: "development",
    client: "Music Venue Live",
    year: "2025–2026",
    category: "Video Streaming / E-commerce",
    summary: "Live music streaming and venue storytelling — performance capture, merch, and fan access in one product surface.",
    description: "In-development streaming and commerce surface for live music venues and artists. Real-time concerts from independent U.S. clubs — multi-cam production, soundboard audio, and community watching together.",
    role: "Product design & development",
    stack: ["Streaming", "E-commerce", "Video"],
    url: "https://stagepass-gtm-insights.vercel.app/",
    screenshots: ["/media/websites/music-venue-live-home.jpg"],
    tone: "dev"
  },
  {
    id: "lifestyle-brand-site",
    title: "Lifestyle Brand Site",
    status: "development",
    client: "Cellora Nutritionals",
    year: "2026",
    category: "Cellular Nutrition",
    summary: "E-commerce and brand site for cellular nutrition — product story, education, and conversion without medical claims.",
    description: "Brand and storefront for Cellora Nutritionals: systems, vitamins, and skin essentials with verified potency and a 30-day money-back guarantee. Clean product hierarchy and partner-safe messaging.",
    role: "Design & front-end",
    stack: ["E-commerce", "Brand system"],
    url: "https://cellora-nutritionals.vercel.app/",
    screenshots: ["/media/websites/lifestyle-brand-home.jpg"],
    tone: "dev"
  },
  {
    id: "lifestyle-brand-ai-tool",
    title: "Lifestyle Brand AI-powered Tool",
    status: "development",
    client: "USANA Brand Partner",
    year: "2026",
    category: "Cellular Nutrition Brand Partner Marketing AI Coach",
    summary: "Compliance-first AI coach for brand partners — product placement, recruiting, and policy-safe content.",
    description: "USANA Brand Partner Success Agent: a compliance-first AI coach that helps partners sell products, place them in service locations, and recruit — without risking distributorship status.",
    role: "Product design · Agent systems",
    stack: ["AI agents", "Compliance", "Content"],
    url: "https://usana-demo-site.vercel.app/",
    screenshots: ["/media/websites/lifestyle-ai-tool-home.jpg"],
    tone: "dev"
  },
  {
    id: "job-board-scout",
    title: "Job Board Site",
    status: "development",
    client: "Scout",
    year: "2026",
    category: "AI-powered personal job search tool",
    summary: "Personal job search automation — matching, tracking, and outreach tooling for executives in transition.",
    description: "Scout Job Search OS: AI-assisted workspace for role matching, application tracking, pipeline, and structured outreach under the user's control.",
    role: "Product design & engineering",
    stack: ["Python", "AI", "Automation", "Vercel"],
    url: "https://scout-repo-gtm-insights.vercel.app/",
    screenshots: ["/media/websites/job-board-scout-home.jpg"],
    tone: "dev"
  },
  {
    id: "county-emergency-response",
    title: "County Emergency Response Site",
    status: "development",
    client: "Calhoun · Meshtastic Command",
    year: "2026",
    category: "AI-powered radio coverage mapping and planning tool",
    summary: "Radio coverage mapping and command placement for county emergency response — clarity for planners who need the map to be right.",
    description: "Meshtastic Command planning surface for Calhoun County: dual EOCs, MCC trailer/truck/jeep placements by sector, CERT, ham, fire stations, and live weather — with coverage reliability overlays.",
    role: "Product design & front-end",
    stack: ["Maps", "GIS", "Mesh radio", "Planning"],
    url: "",
    screenshots: ["/media/websites/county-emergency-home.jpg"],
    tone: "dev"
  }
];
