// Website roster for khristiankline.com
window.KK_DEFAULT_WEBSITES = [
  {
    id: "gtm-insights",
    title: "GTM Insights Group",
    status: "live",
    client: "GTM Insights Group",
    year: "2026",
    category: "Consultant Site",
    summary: "Enterprise go-to-market consulting — digital & web intelligence that turns web properties into a measurable GTM advantage.",
    description: "Specialized consulting site for enterprise GTM teams. The practice delivers actionable digital and web insights so operators can execute go-to-market strategies with precision and measurable impact.\n\nPositioned for Fortune 500 GTM leaders: services, approach, projects, virtual events, and a clear path to book a strategy call.",
    role: "Founder · Strategy, design & front-end",
    stack: ["Next.js", "TypeScript", "Vercel"],
    url: "https://www.gtm-insights.com",
    screenshots: ["/media/websites/gtm-insights-home.jpg"],
    tone: "live"
  },
  {
    id: "watchmen-of-the-streets",
    title: "Watchmen of the Streets",
    status: "live",
    client: "Watchmen of the Streets",
    year: "2025",
    category: "Non-Profit",
    summary: "Homeless outreach of Habit Missions — field work, documentary storytelling, and a calm public presence for a boots-on-the-ground ministry.",
    description: "Nonprofit site for Watchmen of the Streets, a homeless outreach of Habit Missions. The public face balances documentary gravity with practical clarity: mission story, field photography, video, and simple paths to learn more, contact, and support.",
    role: "Design & development",
    stack: ["WordPress", "Custom theme", "Video"],
    url: "https://www.watchmenofthestreets.com",
    screenshots: ["/media/websites/watchmen-home.jpg", "/media/websites/watchmen-action.jpg"],
    tone: "live"
  },
  {
    id: "music-venue-live",
    title: "Music Venue Live",
    status: "development",
    client: "Music Venue Live",
    year: "2025–2026",
    category: "Video Streaming / E-commerce",
    summary: "Live music streaming and venue storytelling — performance capture, merch, and fan access in one product surface.",
    description: "In-development streaming and commerce surface for live music venues and artists. Focus on the room, the set, and the path from discovery to ticket or merch.",
    role: "Product design & development",
    stack: ["Streaming", "E-commerce", "Video"],
    url: "https://www.musicvenuelive.com",
    screenshots: [],
    tone: "dev"
  },
  {
    id: "lifestyle-brand-site",
    title: "Lifestyle Brand Site",
    status: "development",
    client: "Cellora / USANA partner",
    year: "2026",
    category: "Cellular Nutrition",
    summary: "E-commerce and brand site for cellular nutrition — product story, education, and conversion without medical claims.",
    description: "Brand and storefront surface for a cellular nutrition practice. Clean product hierarchy, education modules, and partner-safe messaging.",
    role: "Design & front-end",
    stack: ["E-commerce", "Brand system"],
    url: "",
    screenshots: [],
    tone: "dev"
  },
  {
    id: "lifestyle-brand-ai-tool",
    title: "Lifestyle Brand AI-powered Tool",
    status: "development",
    client: "USANA Brand Partner",
    year: "2026",
    category: "Cellular Nutrition Brand Partner Marketing AI Coach",
    summary: "AI coach for brand partners — compliant captions, product shares, and daily success workflow.",
    description: "Marketing AI coach for nutrition brand partners. Compliance-first content assist that stays inside official product language.",
    role: "Product design · Agent systems",
    stack: ["AI agents", "Compliance", "Content"],
    url: "",
    screenshots: [],
    tone: "dev"
  },
  {
    id: "job-board-scout",
    title: "Job Board Site",
    status: "development",
    client: "Scout",
    year: "2026",
    category: "AI-powered personal job search tool",
    summary: "Personal job search automation — matching, tracking, and outreach tooling for executives in transition.",
    description: "AI-assisted job search workspace: role matching, application tracking, and structured outreach under the user's control.",
    role: "Product design & engineering",
    stack: ["Python", "AI", "Automation", "Vercel"],
    url: "",
    screenshots: [],
    tone: "dev"
  },
  {
    id: "county-emergency-response",
    title: "County Emergency Response Site",
    status: "development",
    client: "County Emergency Response",
    year: "2026",
    category: "AI-powered radio coverage mapping and planning tool",
    summary: "Radio coverage mapping and planning for county emergency response — clarity for planners who need the map to be right.",
    description: "Planning tool for county emergency radio coverage. Mapping, gap analysis, and documentation for field and command teams.",
    role: "Product design & front-end",
    stack: ["Maps", "GIS", "AI", "Planning"],
    url: "",
    screenshots: [],
    tone: "dev"
  }
];
